##
# Plugins
require:
  - standard
  - rubocop-rspec

##
# Defaults: standard-rb
inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.2
  Include:
    - 'lib/*.rb'
    - 'lib/**/*.rb'
    - 'spec/*.rb'

##
# Enabled
Style/FrozenStringLiteralComment:
  Enabled: true
Layout/ArrayAlignment:
  Enabled: false

##
# Disabled
RSpec/FilePath:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/NotToNot:
  Enabled: false
RSpec/EmptyLineAfterHook:
  Enabled: false
RSpec/EmptyLineAfterSubject:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/EmptyLineAfterFinalLet:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
